[[headers]]
  for = "/.well-known/matrix/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
[[headers]]
  for = "/.well-known/openpgpkey/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
