#+TITLE: The AOL of the 2020s
#+DATE:	<2022-02-10 Thu>

I turned 42 a some time ago.  In anticipation of [[https://www.independent.co.uk/life-style/history/42-the-answer-to-life-the-universe-and-everything-2205734.html][attaining the answer
to life, the universe, and everything]], I planned to blog the answer to
the rest of you.  The answer never came, so neither did the blog.  I
needed a new number to credential my writing.  Tonight I discovered I
am about to be a septugenarian in Venutian years.  It's enough time to
have seen several communication platforms come and go, and I've been
called "old" and "crotchety" for avoiding some more modern ones.  I
can't dispute those labels, but I also see that what is hailed as
progress repeats the tragic mistakes of the past.

My online life began on AOL and its walled garden of chat rooms.
Yeah, there was a lot of "[[https://knowyourmeme.com/memes/asl][a/s/l]]", but there were a few non-horny
people talking sharing non-horny things as well.  I was still in high
school, studying German.  With a naughty phrasebook and a sophomoric
wit, my friend and I carefully transcribed, "Hat dir Jemand ins Gehirn
geschissen und vergessen umzurühren?"[fn:1].  We were abruptly
disconnected and banned.  I dusted myself off, grabbed my digital
belongings, and ventured out onto the public internet.

It was marvelous.  I learned about the web setting up [[http://www.scriptarchive.com/wwwboard.html][Matt's Script
Archive]] and talking to others on their boards.  We made [[https://en.wikipedia.org/wiki/Webring][web rings]] and
announced ourselves through web directories like [[https://en.wikipedia.org/wiki/DMOZ][dmoz]] until a
succession of search engines replaced the quaint charms with
magnitudes more utility.  Other founts of wisdom were also indexed,
like [[http://www.searchengineshowdown.com/usenet/deja/][DejaNews]]' archive of Usenet.  The golden eras of mailing lists
and blogs came and went, each building up the digital commons.

In the mid-2010s, [[https://gitter.im/][Gitter]] became all the rage among developers.  To
this day its archives serve as a primary source as to what the hell we
were thinking a few years ago.  Most of the original [[https://github.com/typelevel/cats][Cats]] authors have
moved on, but we can go back and [[https://gitter.im/typelevel/cats/archives/2015/01/29][observe the big bang]].  There are
years of insights there, linked on the issue tracker and indexed by
Google.  These archives were always precarious -- none of us pay to
for their stewardship -- but it was an open product for an open web,
and new cohorts of developers can still learn from it, even after
we've all moved on.

The Gitter UX slowly declined from mediocre to worse.  One by one,
communities retreated from the shabby public square behind the more
posh gates of Slack and Discord.  They're fine for fun and friendship,
but neglect the value of a recorded history.  The help we give no
longer compounds with readers from the future.  The energy bustles
inward, and fewer potential members stumble across us.  Slack and
Discord communities are the AOL of the 2020s, and our best insights
will be flushed down the same pipe as my poop joke of 1996.

That's why I'm scarce on Discord.  I'll still join your Slack, for a
paycheck.  I have high hopes [[https://matrix.org/][Matrix]] will pair a modern UX with an open
foundation, but until then, I'm enjoying this chat hiatus.  I'm
doubling down on a more open community, und ich werde nicht vergessen
umzurühren[fn:2].

* Footnotes

[fn:1] Did someone shit in your brain and forget to stir?
[fn:2] I won't forget to stir.
