name: home-manager

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2.3.2

      - name: "Install Nix️"
        uses: cachix/install-nix-action@v15

      - name: "Install Cachix️"
        uses: cachix/cachix-action@v10
        with:
          name: rossabaker
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
          signingKey: '${{ secrets.CACHIX_SIGNING_KEY }}'

      - name: "Build Home Manager config"
        run: nix build --option access-tokens.github.com ${{secrets.GITHUB_TOKEN}} --json .#homeConfigurations.\"ross.baker@C02Z721ZLVCG\".activationPackage
